### ISSUE TITLE
Styling Issues Checklist

### ISSUE THREAD

**Issue by trinaisartsy** [trinaisartsy/github.io#4]
- [x]  make sure all banners have images
- [x]  sort art to make homepage slideshow appealing
- [x]  fix "home" logo to something more intuitive
- [x] Fix navigation bar color to dark purple
- [x]  Navigation button colors from blue to purple
- [x] Scrollbar color customized?
- [x]  Remove unessecary buttons from nav (Local)
